// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk5BQrKh8v3jH7tYfdE5TPppxfAbpslig',
    appId: '1:1054048991906:web:fea444f90a6ddf82ee35fb',
    messagingSenderId: '1054048991906',
    projectId: 'tragicomic-bd876',
    authDomain: 'tragicomic-bd876.firebaseapp.com',
    storageBucket: 'tragicomic-bd876.appspot.com',
    measurementId: 'G-DFW0B7KHXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXHcfXRApMc27x6GvaM4yA_OhvdnTkfM0',
    appId: '1:1054048991906:android:f23d22cc8887a51fee35fb',
    messagingSenderId: '1054048991906',
    projectId: 'tragicomic-bd876',
    storageBucket: 'tragicomic-bd876.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGCAXGxDfnUNYGqm_0n6GgddUuBHCQWVY',
    appId: '1:1054048991906:ios:3690559e6a3a7a08ee35fb',
    messagingSenderId: '1054048991906',
    projectId: 'tragicomic-bd876',
    storageBucket: 'tragicomic-bd876.appspot.com',
    iosClientId: '1054048991906-m58itiqtvc9nes3se9e158sc7abko4l9.apps.googleusercontent.com',
    iosBundleId: 'com.example.tragicomic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGCAXGxDfnUNYGqm_0n6GgddUuBHCQWVY',
    appId: '1:1054048991906:ios:3690559e6a3a7a08ee35fb',
    messagingSenderId: '1054048991906',
    projectId: 'tragicomic-bd876',
    storageBucket: 'tragicomic-bd876.appspot.com',
    iosClientId: '1054048991906-m58itiqtvc9nes3se9e158sc7abko4l9.apps.googleusercontent.com',
    iosBundleId: 'com.example.tragicomic',
  );
}
